### ISSUE TITLE
请问有cGan的FL相关代码吗

### ISSUE THREAD

**Issue by Neiou8** [Ls-Dai/Pytorch_FL_GAN#1]

**Comment by Ls-Dai** [comment]
你好，请试试 https://github.com/Ls-Dai/Pytorch-Federated-Learning-cGan

**Comment by Ls-Dai** [comment]
https://github.com/Ls-Dai/Pytorch-Federated-Learning-cGan

**Comment by Ls-Dai** [comment]
@Neiou8

**Comment by Ls-Dai** [comment]
@Neiou8  https://github.com/Ls-Dai/Pytorch-Federated-Learning-cGan

**Comment by Neiou8** [comment]
非常感谢

**Comment by Ls-Dai** [comment]
> 非常感谢

不用客气 ：）
